var Holder=Holder||{};
(function(g,k){function v(a){a=a.match(/^(\W)?(.*)/);a=document["getElement"+(a[1]?"#"==a[1]?"ById":"sByClassName":"sByTagName")](a[2]);var b=[];null!=a&&(a.length?b=a:0==a.length?b=a:b=[a]);return b}function q(a,b){var c={},f;for(f in a)c[f]=a[f];for(var d in b)c[d]=b[d];return c}function x(a,b,c,f){var d=[b.height,b.width].sort(),e=Math.round(d[1]/16);Math.round(d[0]/16);var d=Math.max(c.size,e),e=b.width*f,g=b.height*f,h=c.font?c.font:"sans-serif";l.width=e;l.height=g;a.textAlign="center";a.textBaseline=
"middle";a.fillStyle=c.background;a.fillRect(0,0,e,g);a.fillStyle=c.foreground;a.font="bold "+d+"px "+h;b=c.text?c.text:b.width+"x"+b.height;1<a.measureText(b).width/e&&(d=c.size/(a.measureText(b).width/e));a.font="bold "+d*f+"px "+h;a.fillText(b,e/2,g/2,e);return l.toDataURL("image/png")}function y(a,b,c,f){var d=c.dimensions,e=c.theme,g=c.text?decodeURIComponent(c.text):c.text,h=d.width+"x"+d.height,e=g?q(e,{text:g}):e,e=c.font?q(e,{font:c.font}):e,k=1;window.devicePixelRatio&&1<window.devicePixelRatio&&
(k=window.devicePixelRatio);if("image"==a){b.setAttribute("data-src",f);b.setAttribute("alt",g?g:e.text?e.text+" ["+h+"]":h);if(m||!c.auto)b.style.width=d.width+"px",b.style.height=d.height+"px";m?b.style.backgroundColor=e.background:b.setAttribute("src",x(z,d,e,k))}else m||(b.style.backgroundImage="url("+x(z,d,e,k)+")",b.style.backgroundSize=d.width+"px "+d.height+"px")}function G(a,b){var c=b.dimensions,f=b.theme,d=b.text,c=c.width+"x"+c.height,f=d?q(f,{text:d}):f,e=document.createElement("div");
e.style.backgroundColor=f.background;e.style.color=f.foreground;e.className=a.className+" holderjs-fluid";e.style.width=b.dimensions.width+(0<b.dimensions.width.indexOf("%")?"":"px");e.style.height=b.dimensions.height+(0<b.dimensions.height.indexOf("%")?"":"px");e.id=a.id;a.style.width=0;a.style.height=0;f.text?e.appendChild(document.createTextNode(f.text)):(e.appendChild(document.createTextNode(c)),r.push(e),setTimeout(s,0));a.parentNode.insertBefore(e,a.nextSibling);window.jQuery&&jQuery(function(b){b(a).on("load",
function(){a.style.width=e.style.width;a.style.height=e.style.height;b(a).show();b(e).remove()})})}function s(){for(i in r)if(r.hasOwnProperty(i)){var a=r[i],b=a.firstChild;a.style.lineHeight=a.offsetHeight+"px";b.data=a.offsetWidth+"x"+a.offsetHeight}}function A(a,b){var c={theme:t.themes.gray},f=!1;sl=a.length;for(j=0;j<sl;j++){var d=a[j];g.flags.dimensions.match(d)?(f=!0,c.dimensions=g.flags.dimensions.output(d)):g.flags.fluid.match(d)?(f=!0,c.dimensions=g.flags.fluid.output(d),c.fluid=!0):g.flags.colors.match(d)?
c.theme=g.flags.colors.output(d):b.themes[d]?c.theme=b.themes[d]:g.flags.text.match(d)?c.text=g.flags.text.output(d):g.flags.font.match(d)?c.font=g.flags.font.output(d):g.flags.auto.match(d)&&(c.auto=!0)}return f?c:!1}var B=!1,m=!1,l=document.createElement("canvas");document.getElementsByClassName||(document.getElementsByClassName=function(a){var b=document,c,f=[];if(b.querySelectorAll)return b.querySelectorAll("."+a);if(b.evaluate)for(b=b.evaluate(".//*[contains(concat(' ', @class, ' '), ' "+a+" ')]",
b,null,0,null);c=b.iterateNext();)f.push(c);else{b=b.getElementsByTagName("*");a=RegExp("(^|\\s)"+a+"(\\s|$)");for(c=0;c<b.length;c++)a.test(b[c].className)&&f.push(b[c])}return f});window.getComputedStyle||(window.getComputedStyle=function(a){return this.el=a,this.getPropertyValue=function(b){var c=/(\-([a-z]){1})/g;return"float"==b&&(b="styleFloat"),c.test(b)&&(b=b.replace(c,function(a,b,c){return c.toUpperCase()})),a.currentStyle[b]?a.currentStyle[b]:null},this});Object.prototype.hasOwnProperty||
(Object.prototype.hasOwnProperty=function(a){var b=this.__proto__||this.constructor.prototype;return a in this&&(!(a in b)||b[a]!==this[a])});if(l.getContext)if(0>l.toDataURL("image/png").indexOf("data:image/png"))m=!0;else var z=l.getContext("2d");else m=!0;var r=[],t={domain:"holder.js",images:"img",bgnodes:".holderjs",themes:{gray:{background:"#eee",foreground:"#aaa",size:12},social:{background:"#3a5a97",foreground:"#fff",size:12},industrial:{background:"#434A52",foreground:"#C2F200",size:12}},
stylesheet:".holderjs-fluid {font-size:16px;font-weight:bold;text-align:center;font-family:sans-serif;margin:0}"};g.flags={dimensions:{regex:/^(\d+)x(\d+)$/,output:function(a){a=this.regex.exec(a);return{width:+a[1],height:+a[2]}}},fluid:{regex:/^([0-9%]+)x([0-9%]+)$/,output:function(a){a=this.regex.exec(a);return{width:a[1],height:a[2]}}},colors:{regex:/#([0-9a-f]{3,})\:#([0-9a-f]{3,})/i,output:function(a){a=this.regex.exec(a);return{size:t.themes.gray.size,foreground:"#"+a[2],background:"#"+a[1]}}},
text:{regex:/text\:(.*)/,output:function(a){return this.regex.exec(a)[1]}},font:{regex:/font\:(.*)/,output:function(a){return this.regex.exec(a)[1]}},auto:{regex:/^auto$/}};for(var n in g.flags)g.flags.hasOwnProperty(n)&&(g.flags[n].match=function(a){return a.match(this.regex)});g.add_theme=function(a,b){null!=a&&null!=b&&(t.themes[a]=b);return g};g.add_image=function(a,b){var c=v(b);if(c.length)for(var f=0,d=c.length;f<d;f++){var e=document.createElement("img");e.setAttribute("data-src",a);c[f].appendChild(e)}return g};
g.run=function(a){a=q(t,a);var b=[];imageNodes=a.images instanceof window.NodeList?a.images:a.images instanceof window.Node?[a.images]:v(a.images);bgnodes=a.elements instanceof window.NodeList?a.bgnodes:a.bgnodes instanceof window.Node?[a.bgnodes]:v(a.bgnodes);B=!0;d=0;for(f=imageNodes.length;d<f;d++)b.push(imageNodes[d]);var c=document.getElementById("holderjs-style");c||(c=document.createElement("style"),c.setAttribute("id","holderjs-style"),c.type="text/css",document.getElementsByTagName("head")[0].appendChild(c));
c.styleSheet?c.styleSheet+=a.stylesheet:c.textContent+=a.stylesheet;for(var c=RegExp(a.domain+'/(.*?)"?\\)'),f=bgnodes.length,d=0;d<f;d++){var e=window.getComputedStyle(bgnodes[d],null).getPropertyValue("background-image"),h=e.match(c);h&&(h=A(h[1].split("/"),a))&&y("background",bgnodes[d],h,e)}f=b.length;for(d=0;d<f;d++)e=b[d].getAttribute("src")||b[d].getAttribute("data-src"),null!=e&&0<=e.indexOf(a.domain)&&(h=A(e.substr(e.lastIndexOf(a.domain)+a.domain.length+1).split("/"),a))&&(h.fluid?G(b[d],
h,e):y("image",b[d],h,e));return g};var C=function(){window.addEventListener?(window.addEventListener("resize",s,!1),window.addEventListener("orientationchange",s,!1)):window.attachEvent("onresize",s);B||g.run()},D=!1;n=!0;var h=k.document,E=h.documentElement,w=h.addEventListener?"addEventListener":"attachEvent",H=h.addEventListener?"removeEventListener":"detachEvent",u=h.addEventListener?"":"on",p=function(a){("readystatechange"!=a.type||"complete"==h.readyState)&&(("load"==a.type?k:h)[H](u+a.type,
p,!1),!D&&(D=!0)&&C.call(k,null))},F=function(){try{E.doScroll("left")}catch(a){setTimeout(F,50);return}p("poll")};if("complete"==h.readyState)C.call(k,"lazy");else{if(h.createEventObject&&E.doScroll){try{n=!k.frameElement}catch(I){}n&&F()}h[w](u+"DOMContentLoaded",p,!1);h[w](u+"readystatechange",p,!1);k[w](u+"load",p,!1)}"function"===typeof define&&define.amd&&define("Holder",[],function(){return g})})(Holder,window);
